force-app/main/default/objects/New_Asset__e/New_Asset__e.object-meta.xml
<CustomObject>
    <label>New Asset</label>
    <pluralLabel>New Assets</pluralLabel>
</CustomObject>

force-app/main/default/objects/New_Asset__e/fields/Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID__c</fullName>
    <label>Asset ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Asset__e/fields/Asset_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Asset_Install_Date__c</fullName>
    <label>Asset Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NewAssetTriggerHandler.cls
public with sharing class NewAssetTriggerHandler {
    public static void afterInsert(List<New_Asset__e> events) {

        List<AssetWarranty> assetWarranties = new List<AssetWarranty>();

        for(New_Asset__e event : events) {
            assetWarranties.add(
                    new AssetWarranty(
                            AssetId = event.Asset_ID__c,
                            StartDate = event.Asset_Install_Date__c)
            );
        }
        insert assetWarranties;
    }
}